name: Upload via FTP
on:
  pull_request:
    branches: 
      - master
      - develop
  push:
    branches: 
      - master
      - develop
jobs:
  FTP-Action:
    name: FTP-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build Project
      run: |
        npm install
        npm run build --if-present
    - name: List output files
      run: ls
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME_SSH }}
        password: ${{ secrets.PASSWORD_SSH }}
        port: ${{ secrets.PORT_SSH }}
        script: sudo chmod 777 -R /opt && rm -rf /opt/tomcat/webapps/srj9
    
    - name: Deploy FTP
      uses: sebastianpopp/ftp-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist"
        remoteDir: "/opt/tomcat/webapps/srj9"
